paths: ["vendor/certificationy/symfony-pack/data", "vendor/certificationy/php-pack/data", 'data/php']
manifest_uri: "https://raw.githubusercontent.com/TheRatG/certificationy-cli/gh-pages/manifest.json"
